services:
  db:
    image: postgres:latest
    container_name: postgres-ucredit
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=omar
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ucredit
    command: sh -c "python manage.py runserver 0.0.0.0:8000 --settings=creditoapp.settings.prod"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres-data: